ai:
  accept_undo_offers:
    no_stake: true
    stake: false
  max_ai_games: 3
  min_move_wait: 1
  name_format: '[AI]<NAME>'
  lose_on_fail: false
auto_teleport_on_join: true
auto_teleport_on_start: true
auto_delete:
  finished: 15 sec
  not_started: 1 min 30 sec
  running: 28 days
autostart: true
broadcast_results: true
coloured_console: true
database:
  driver: sqlite
  host: localhost
  user: checkers
  password: checkers
  port: 3306
  name: checkers
  table_prefix: checkers_
default_rules:
  8: EnglishDraughts
  10: InternationalDraughts
  12: CanadianCheckers
dynmap:
  enabled: true
  hide_by_default: false
  min_zoom: 0
  layer_priority: 1
effects:
  game_lost: sound,name=enderman_death
  game_won: sound,name=level_up
  piece_captured: explosion
  piece_moved: sound,name=item_pickup
  piece_riding: true
  piece_selected: sound,name=note_sticks
  piece_unselected: sound,name=note_bass
  teleport_in: effect,name=ender_signal
  teleport_out: effect,name=smoke,data=4
  volume: 1.0
flying:
  allowed: true
  captive: true
  auto: false
  upper_limit: 50
  outer_limit: 25
  fly_speed: 0.2
  walk_speed: 0.2
forced_jump: true
forfeit_timeout: 5 min
ladder:
  initial_position: 1000
league:
  draw_points: 1
  loss_points: 0
  win_points: 2
locale: default
log_level: info
max_moves_without_capture: 50
mcstats: true
open_invite_cooldown: 1 min 30 sec
pager:
  lines: 0
protection:
  no_building: true
  no_burning: true
  no_creatures: true
  no_explosions: true
  no_misc_damage: true
  no_pvp: true
stake:
  default: 0.0
  largeIncrement: 10.0
  max: -1
  smallIncrement: 1.0
teleporting: true
time_control:
  default: none
  warn_seconds: 30
wand_item: '*'
